import type { TemplateSettings, AppSettings } from '@/types'

// ─── Languages ───────────────────────────────────────────────────────────────

export const SUPPORTED_LANGUAGES = [
  { code: 'ar', label: 'العربية' },
  { code: 'cs', label: 'Čeština' },
  { code: 'de', label: 'Deutsch' },
  { code: 'el', label: 'Ελληνικά' },
  { code: 'en', label: 'English' },
  { code: 'es', label: 'Español' },
  { code: 'fi', label: 'Suomi' },
  { code: 'fr', label: 'Français' },
  { code: 'hr', label: 'Hrvatski' },
  { code: 'hu', label: 'Magyar' },
  { code: 'it', label: 'Italiano' },
  { code: 'ja', label: '日本語' },
  { code: 'nl', label: 'Nederlands' },
  { code: 'no', label: 'Norsk' },
  { code: 'pl', label: 'Polski' },
  { code: 'pt', label: 'Português' },
  { code: 'ru', label: 'Русский' },
  { code: 'sk', label: 'Slovenčina' },
  { code: 'sl', label: 'Slovenščina' },
  { code: 'sv', label: 'Svenska' },
  { code: 'tr', label: 'Türkçe' },
  { code: 'zh', label: '中文' },
] as const

/** Sentinel value meaning "follow the system/browser language" */
export const LANGUAGE_AUTO = 'auto'

// ─── Accent colors ───────────────────────────────────────────────────────────

export const ACCENT_PRESETS = [
  { id: 'blue',    hex: '#3b82f6', hover: '#2563eb', subtle: '#eff6ff', ring: '#93c5fd' },
  { id: 'sky',     hex: '#0ea5e9', hover: '#0284c7', subtle: '#f0f9ff', ring: '#7dd3fc' },
  { id: 'cyan',    hex: '#06b6d4', hover: '#0891b2', subtle: '#ecfeff', ring: '#67e8f9' },
  { id: 'indigo',  hex: '#6366f1', hover: '#4f46e5', subtle: '#eef2ff', ring: '#a5b4fc' },
  { id: 'violet',  hex: '#8b5cf6', hover: '#7c3aed', subtle: '#f5f3ff', ring: '#c4b5fd' },
  { id: 'purple',  hex: '#a855f7', hover: '#9333ea', subtle: '#faf5ff', ring: '#d8b4fe' },
  { id: 'fuchsia', hex: '#d946ef', hover: '#c026d3', subtle: '#fdf4ff', ring: '#e879f9' },
  { id: 'pink',    hex: '#ec4899', hover: '#db2777', subtle: '#fdf2f8', ring: '#f9a8d4' },
  { id: 'rose',    hex: '#f43f5e', hover: '#e11d48', subtle: '#fff1f2', ring: '#fda4af' },
  { id: 'red',     hex: '#ef4444', hover: '#dc2626', subtle: '#fef2f2', ring: '#fca5a5' },
  { id: 'amber',   hex: '#f59e0b', hover: '#d97706', subtle: '#fffbeb', ring: '#fcd34d' },
  { id: 'orange',  hex: '#f97316', hover: '#ea580c', subtle: '#fff7ed', ring: '#fdba74' },
  { id: 'yellow',  hex: '#eab308', hover: '#ca8a04', subtle: '#fefce8', ring: '#fde047' },
  { id: 'lime',    hex: '#84cc16', hover: '#65a30d', subtle: '#f7fee7', ring: '#bef264' },
  { id: 'green',   hex: '#22c55e', hover: '#16a34a', subtle: '#f0fdf4', ring: '#86efac' },
  { id: 'emerald', hex: '#10b981', hover: '#059669', subtle: '#ecfdf5', ring: '#6ee7b7' },
  { id: 'teal',    hex: '#14b8a6', hover: '#0d9488', subtle: '#f0fdfa', ring: '#5eead4' },
  { id: 'slate',   hex: '#64748b', hover: '#475569', subtle: '#f8fafc', ring: '#94a3b8' },
] as const

export const DEFAULT_ACCENT_COLOR = ACCENT_PRESETS[0].hex

// ─── Theme ───────────────────────────────────────────────────────────────────

export const THEME_VARS = {
  light: {
    '--bg-primary':   '#ffffff',
    '--bg-secondary': '#f8f9fa',
    '--text-primary':   '#1a1a1a',
    '--text-secondary': '#6b7280',
    '--border': '#e5e7eb',
  },
  dark: {
    '--bg-primary':   '#1a1a1a',
    '--bg-secondary': '#2d2d2d',
    '--text-primary':   '#f9fafb',
    '--text-secondary': '#9ca3af',
    '--border': '#374151',
  },
} as const

// ─── Defaults ────────────────────────────────────────────────────────────────

export const DEFAULT_APP_SETTINGS: AppSettings = {
  language: 'auto',
  theme: 'auto',
  accentColor: DEFAULT_ACCENT_COLOR,
}

export const DEFAULT_TEMPLATE_SETTINGS: TemplateSettings = {
  pageColor:       '#ffffff',
  backgroundColor: '#f1f1f1',
  contentWidth: 600,
  fontFamily: 'Arial, sans-serif',
  fontSize: 14,
  fontColor: '#4c4c4c',
  lineHeight: 1.25,
  padding: '2px',
  defaultBorderRadius: '8px',
  defaultBorderWidth: '1px',
  defaultBorderStyle: 'solid',
  borderColor:      '#e0e0ff',
  primaryColor:     '#3465d7',
  secondaryColor:   '#8b5cf6',
  alternativeColor: '#10b981',
  designColor:      '#f59e0b',
  brandColor:       '#1e293b',
}

// ─── Block defaults ───────────────────────────────────────────────────────────

export const DEFAULT_BLOCK_PROPS = {
  text: {
    content: '',
    align: 'left',
    color: 'fontColor',
    fontSize: '',
    fontFamily: '',
    innerPadding: '+4',
    borderRadius: '',
    sectionBg: 'backgroundColor',
    outerPadding: '',
    borderWidth: '',
    borderColor: 'borderColor',
    borderStyle: '',
  },
  image: {
    src: '',
    alt: '',
    align: 'center',
    width: '100%',
    innerPadding: '+4',
    borderRadius: '',
    sectionBg: 'backgroundColor',
    outerPadding: '',
    borderWidth: '',
    borderColor: 'borderColor',
    borderStyle: '',
  },
  button: {
    text: '',
    href: 'https://...',
    align: 'center',
    backgroundColor: 'primaryColor',
    color: 'pageColor',
    fontSize: '',
    fontFamily: '',
    padding: '25px 10px',
    secInnerPadding: '+4',
    borderRadius: '8px',
    sectionBg: 'backgroundColor',
    outerPadding: '',
    borderWidth: '',
    borderColor: 'borderColor',
    borderStyle: '',
  },

  divider: {
    borderWidth: '1px',
    borderColor: 'borderColor',
    borderStyle: '',
    innerPadding: '+4',
    padding: '25px 10px',
    sectionBg: 'backgroundColor',
    outerPadding: '',
  },
  columns: {
    columns: 2,
    padding: '4px',
    minHeight: 'auto',
    verticalAlign: 'top',
    sectionBg: 'pageColor',
    columnProps: [
      { col: '1', align: 'left', verticalAlign: 'top', backgroundColor: '', borderRadius: '', padding: '0px', borderWidth: '', borderColor: 'borderColor', borderStyle: 'solid' },
      { col: '2', align: 'left', verticalAlign: 'top', backgroundColor: '', borderRadius: '', padding: '0px', borderWidth: '', borderColor: 'borderColor', borderStyle: 'solid' },
      { col: '3', align: 'left', verticalAlign: 'top', backgroundColor: '', borderRadius: '', padding: '0px', borderWidth: '', borderColor: 'borderColor', borderStyle: 'solid' },
    ],
  },
  social: {
    align: 'center',
    iconSize: '28',
    innerPadding: '+4',
    padding: '25px 10px',
    sectionBg: 'backgroundColor',
    outerPadding: '',
    iconCount: '3',
    separator: '  ',
    icon1Type: 'facebook', icon1Color: 'pageColor', icon1Shape: 'rounded', icon1Bg: 'fontColor', icon1Href: '',
    icon2Type: 'twitter',  icon2Color: 'pageColor', icon2Shape: 'rounded', icon2Bg: 'fontColor', icon2Href: '',
    icon3Type: 'instagram', icon3Color: 'pageColor', icon3Shape: 'rounded', icon3Bg: 'fontColor', icon3Href: '',
  },
  navbar: {
    linkCount: '3',
    link1Text: '',    link1Href: 'https://...',
    link2Text: '',    link2Href: 'https://...',
    link3Text: '',    link3Href: 'https://...',
    link4Text: '',        link4Href: 'https://...',
    link5Text: '',        link5Href: 'https://...',
    link6Text: '',        link6Href: 'https://...',
    align: 'center',
    color: 'fontColor',
    fontSize: '',
    fontFamily: '',
    separator: ' | ',
    innerPadding: '+4',
    padding: '25px 10px',
    sectionBg: 'backgroundColor',
    outerPadding: '',
  },
  hero: {
    src: '',
    height: '200px',
    backgroundColor: 'backgroundColor',
    backgroundPosition: 'center center',
    textAlign: 'center',
    verticalAlign: 'middle',
    line1Text: '',
    line1Color: 'fontColor',
    line1FontSize: '+18',
    line1FontFamily: '',
    line2Text: '',
    line2Color: 'fontColor',
    line2FontSize: '+4',
    line2FontFamily: '',
    innerPadding: '+4',
    padding: '20px 25px',
    sectionBg: 'backgroundColor',
    outerPadding: '',
    secBorderRadius: '',
    secBorderWidth: '',
    secBorderColor: 'borderColor',
    secBorderStyle: '',
  },
  video: {
    src: '',
    thumbnailSrc: '',
    alt: '',
    align: 'center',
    innerPadding: '+4',
    padding: '10px 4px',
    sectionBg: 'backgroundColor',
    borderRadius: '',
    outerPadding: '',
    borderWidth: '',
    borderColor: 'borderColor',
    borderStyle: '',
  },
  countdown: {
    targetDate: '',
    showSeconds: 'true',
    labelDays: 'Days',
    labelHours: 'Hours',
    labelMinutes: 'Minutes',
    labelSeconds: 'Seconds',
    bgColor: 'primaryColor',
    textColor: 'backgroundColor',
    labelColor: 'fontColor',
    fontFamily: '',
    fontSize: '+18',
    fontStyle: 'bold',
    labelFontFamily: '',
    labelFontSize: '-2',
    labelFontStyle: '',
    align: 'center',
    innerPadding: '+4',
    padding: '16px 25px',
    sectionBg: 'backgroundColor',
    outerPadding: '',
  },
  accordion: {
    faqCount: '3',
    faq1Question: '', faq1Answer: '',
    faq2Question: '', faq2Answer: '',
    faq3Question: '', faq3Answer: '',
    faq4Question: '', faq4Answer: '',
    faq5Question: '', faq5Answer: '',
    faq6Question: '', faq6Answer: '',
    faq7Question: '', faq7Answer: '',
    faq8Question: '', faq8Answer: '',
    fontFamily: '',
    fontSize: '',
    questionFontStyle: 'bold',
    answerFontStyle: '',
    answerFontFamily: '',
    answerFontSize: '',
    answerColor: 'fontColor',
    color: 'fontColor',
    accordionBorderWidth: '1px',
    accordionBorderColor: 'borderColor',
    accordionBorderStyle: 'solid',
    padding: '+4',
    sectionBg: 'backgroundColor',
    outerPadding: '',
  },
  quote: {
    text: '',
    author: '',
    authorPrefix: '—',
    accentColor: 'primaryColor',
    textColor: 'fontColor',
    authorColor: 'fontColor',
    authorFontSize: '',
    authorFontStyle: '',
    authorFontFamily: '',
    fontStyle: 'italic',
    fontFamily: '',
    quoteStyle: 'quotes',
    align: 'left',
    innerPadding: '+4',
    padding: '25px 10px',
    sectionBg: 'backgroundColor',
    bgColor: 'backgroundColor',
    outerPadding: '',
    borderWidth: '',
    borderColor: 'borderColor',
    borderStyle: '',
  },
} as const
