use tauri::menu::{Menu, MenuItem, PredefinedMenuItem, Submenu};
use tauri::Emitter;
use sys_locale::get_locale;

const APP_TARGET: &str = env!("APP_TARGET");

#[tauri::command]
fn app_target() -> &'static str {
    APP_TARGET
}

/// Returns the two-letter language code of the current system locale (e.g. "de", "en", "fr").
fn system_lang() -> String {
    get_locale()
        .unwrap_or_else(|| "en".to_string())
        .to_lowercase()
        .chars()
        .take(2)
        .collect()
}

struct MenuStrings {
    about:          &'static str,
    check_updates:  &'static str,
    services:       &'static str,
    hide:           &'static str,
    hide_others:    &'static str,
    show_all:       &'static str,
    quit:           &'static str,
    edit:           &'static str,
    undo:           &'static str,
    redo:           &'static str,
    cut:            &'static str,
    copy:           &'static str,
    paste:          &'static str,
    select_all:     &'static str,
    view:           &'static str,
    fullscreen:     &'static str,
    window:         &'static str,
    minimize:       &'static str,
    zoom:           &'static str,
    close_window:   &'static str,
}

fn menu_strings(lang: &str) -> MenuStrings {
    match lang {
        "de" => MenuStrings {
            about:         "Über Visemte",
            check_updates: "Nach Updates suchen\u{2026}",
            services:      "Dienste",
            hide:          "Visemte ausblenden",
            hide_others:   "Andere ausblenden",
            show_all:      "Alle einblenden",
            quit:          "Visemte beenden",
            edit:          "Bearbeiten",
            undo:          "Rückgängig",
            redo:          "Wiederholen",
            cut:           "Ausschneiden",
            copy:          "Kopieren",
            paste:         "Einsetzen",
            select_all:    "Alles auswählen",
            view:          "Darstellung",
            fullscreen:    "Vollbild ein/aus",
            window:        "Fenster",
            minimize:      "Im Dock ablegen",
            zoom:          "Zoomen",
            close_window:  "Fenster schließen",
        },
        "fr" => MenuStrings {
            about:         "À propos de Visemte",
            check_updates: "Rechercher des mises à jour\u{2026}",
            services:      "Services",
            hide:          "Masquer Visemte",
            hide_others:   "Masquer les autres",
            show_all:      "Tout afficher",
            quit:          "Quitter Visemte",
            edit:          "Édition",
            undo:          "Annuler",
            redo:          "Rétablir",
            cut:           "Couper",
            copy:          "Copier",
            paste:         "Coller",
            select_all:    "Tout sélectionner",
            view:          "Présentation",
            fullscreen:    "Activer/désactiver le mode plein écran",
            window:        "Fenêtre",
            minimize:      "Placer dans le Dock",
            zoom:          "Zoom",
            close_window:  "Fermer la fenêtre",
        },
        "es" => MenuStrings {
            about:         "Acerca de Visemte",
            check_updates: "Buscar actualizaciones\u{2026}",
            services:      "Servicios",
            hide:          "Ocultar Visemte",
            hide_others:   "Ocultar otros",
            show_all:      "Mostrar todo",
            quit:          "Salir de Visemte",
            edit:          "Edición",
            undo:          "Deshacer",
            redo:          "Rehacer",
            cut:           "Cortar",
            copy:          "Copiar",
            paste:         "Pegar",
            select_all:    "Seleccionar todo",
            view:          "Vista",
            fullscreen:    "Activar/desactivar pantalla completa",
            window:        "Ventana",
            minimize:      "Minimizar",
            zoom:          "Ampliar",
            close_window:  "Cerrar ventana",
        },
        "it" => MenuStrings {
            about:         "Informazioni su Visemte",
            check_updates: "Verifica aggiornamenti\u{2026}",
            services:      "Servizi",
            hide:          "Nascondi Visemte",
            hide_others:   "Nascondi altri",
            show_all:      "Mostra tutti",
            quit:          "Esci da Visemte",
            edit:          "Modifica",
            undo:          "Annulla",
            redo:          "Ripeti",
            cut:           "Taglia",
            copy:          "Copia",
            paste:         "Incolla",
            select_all:    "Seleziona tutto",
            view:          "Visualizza",
            fullscreen:    "Attiva/disattiva schermo intero",
            window:        "Finestra",
            minimize:      "Minimizza",
            zoom:          "Zoom",
            close_window:  "Chiudi finestra",
        },
        "pt" => MenuStrings {
            about:         "Sobre o Visemte",
            check_updates: "Verificar atualizações\u{2026}",
            services:      "Serviços",
            hide:          "Ocultar Visemte",
            hide_others:   "Ocultar outros",
            show_all:      "Mostrar tudo",
            quit:          "Sair do Visemte",
            edit:          "Editar",
            undo:          "Desfazer",
            redo:          "Refazer",
            cut:           "Cortar",
            copy:          "Copiar",
            paste:         "Colar",
            select_all:    "Selecionar tudo",
            view:          "Visualizar",
            fullscreen:    "Ativar/desativar tela cheia",
            window:        "Janela",
            minimize:      "Minimizar",
            zoom:          "Zoom",
            close_window:  "Fechar janela",
        },
        "nl" => MenuStrings {
            about:         "Over Visemte",
            check_updates: "Controleer op updates\u{2026}",
            services:      "Services",
            hide:          "Verberg Visemte",
            hide_others:   "Verberg anderen",
            show_all:      "Toon alles",
            quit:          "Stop Visemte",
            edit:          "Bewerken",
            undo:          "Ongedaan maken",
            redo:          "Opnieuw",
            cut:           "Knippen",
            copy:          "Kopiëren",
            paste:         "Plakken",
            select_all:    "Alles selecteren",
            view:          "Weergave",
            fullscreen:    "Volledig scherm in-/uitschakelen",
            window:        "Venster",
            minimize:      "Minimaliseren",
            zoom:          "Zoomen",
            close_window:  "Venster sluiten",
        },
        "pl" => MenuStrings {
            about:         "O Visemte",
            check_updates: "Sprawdź aktualizacje\u{2026}",
            services:      "Usługi",
            hide:          "Ukryj Visemte",
            hide_others:   "Ukryj inne",
            show_all:      "Pokaż wszystkie",
            quit:          "Zakończ Visemte",
            edit:          "Edycja",
            undo:          "Cofnij",
            redo:          "Ponów",
            cut:           "Wytnij",
            copy:          "Kopiuj",
            paste:         "Wklej",
            select_all:    "Zaznacz wszystko",
            view:          "Widok",
            fullscreen:    "Włącz/wyłącz pełny ekran",
            window:        "Okno",
            minimize:      "Minimalizuj",
            zoom:          "Powiększ",
            close_window:  "Zamknij okno",
        },
        "ru" => MenuStrings {
            about:         "О программе Visemte",
            check_updates: "Проверить обновления\u{2026}",
            services:      "Службы",
            hide:          "Скрыть Visemte",
            hide_others:   "Скрыть остальные",
            show_all:      "Показать все",
            quit:          "Завершить Visemte",
            edit:          "Правка",
            undo:          "Отменить",
            redo:          "Повторить",
            cut:           "Вырезать",
            copy:          "Копировать",
            paste:         "Вставить",
            select_all:    "Выбрать все",
            view:          "Вид",
            fullscreen:    "Полноэкранный режим",
            window:        "Окно",
            minimize:      "В Dock",
            zoom:          "Масштаб",
            close_window:  "Закрыть окно",
        },
        "tr" => MenuStrings {
            about:         "Visemte Hakkında",
            check_updates: "Güncellemeleri Kontrol Et\u{2026}",
            services:      "Servisler",
            hide:          "Visemte'yi Gizle",
            hide_others:   "Diğerlerini Gizle",
            show_all:      "Tümünü Göster",
            quit:          "Visemte'den Çık",
            edit:          "Düzenle",
            undo:          "Geri Al",
            redo:          "Yinele",
            cut:           "Kes",
            copy:          "Kopyala",
            paste:         "Yapıştır",
            select_all:    "Tümünü Seç",
            view:          "Görünüm",
            fullscreen:    "Tam Ekranı Aç/Kapat",
            window:        "Pencere",
            minimize:      "Küçült",
            zoom:          "Yakınlaştır",
            close_window:  "Pencereyi Kapat",
        },
        "ja" => MenuStrings {
            about:         "Visemteについて",
            check_updates: "アップデートを確認\u{2026}",
            services:      "サービス",
            hide:          "Visemteを隠す",
            hide_others:   "ほかを隠す",
            show_all:      "すべてを表示",
            quit:          "Visemteを終了",
            edit:          "編集",
            undo:          "取り消す",
            redo:          "やり直す",
            cut:           "カット",
            copy:          "コピー",
            paste:         "ペースト",
            select_all:    "すべてを選択",
            view:          "表示",
            fullscreen:    "フルスクリーン切替",
            window:        "ウインドウ",
            minimize:      "しまう",
            zoom:          "ズーム",
            close_window:  "ウインドウを閉じる",
        },
        "zh" => MenuStrings {
            about:         "关于 Visemte",
            check_updates: "检查更新\u{2026}",
            services:      "服务",
            hide:          "隐藏 Visemte",
            hide_others:   "隐藏其他",
            show_all:      "全部显示",
            quit:          "退出 Visemte",
            edit:          "编辑",
            undo:          "撤销",
            redo:          "重做",
            cut:           "剪切",
            copy:          "拷贝",
            paste:         "粘贴",
            select_all:    "全选",
            view:          "显示",
            fullscreen:    "切换全屏幕",
            window:        "窗口",
            minimize:      "最小化",
            zoom:          "缩放",
            close_window:  "关闭窗口",
        },
        "ar" => MenuStrings {
            about:         "حول Visemte",
            check_updates: "التحقق من التحديثات\u{2026}",
            services:      "الخدمات",
            hide:          "إخفاء Visemte",
            hide_others:   "إخفاء الآخرين",
            show_all:      "إظهار الكل",
            quit:          "إنهاء Visemte",
            edit:          "تحرير",
            undo:          "تراجع",
            redo:          "إعادة",
            cut:           "قص",
            copy:          "نسخ",
            paste:         "لصق",
            select_all:    "تحديد الكل",
            view:          "عرض",
            fullscreen:    "تبديل ملء الشاشة",
            window:        "نافذة",
            minimize:      "تصغير",
            zoom:          "تكبير/تصغير",
            close_window:  "إغلاق النافذة",
        },
        "cs" => MenuStrings {
            about:         "O aplikaci Visemte",
            check_updates: "Zkontrolovat aktualizace\u{2026}",
            services:      "Služby",
            hide:          "Skrýt Visemte",
            hide_others:   "Skrýt ostatní",
            show_all:      "Zobrazit vše",
            quit:          "Ukončit Visemte",
            edit:          "Úpravy",
            undo:          "Zpět",
            redo:          "Znovu",
            cut:           "Vyjmout",
            copy:          "Kopírovat",
            paste:         "Vložit",
            select_all:    "Vybrat vše",
            view:          "Zobrazení",
            fullscreen:    "Přepnout celou obrazovku",
            window:        "Okno",
            minimize:      "Minimalizovat",
            zoom:          "Lupa",
            close_window:  "Zavřít okno",
        },
        "sk" => MenuStrings {
            about:         "O aplikácii Visemte",
            check_updates: "Skontrolovať aktualizácie\u{2026}",
            services:      "Služby",
            hide:          "Skryť Visemte",
            hide_others:   "Skryť ostatné",
            show_all:      "Zobraziť všetko",
            quit:          "Ukončiť Visemte",
            edit:          "Úpravy",
            undo:          "Späť",
            redo:          "Znova",
            cut:           "Vystrihnúť",
            copy:          "Kopírovať",
            paste:         "Vložiť",
            select_all:    "Vybrať všetko",
            view:          "Zobrazenie",
            fullscreen:    "Prepnúť celú obrazovku",
            window:        "Okno",
            minimize:      "Minimalizovať",
            zoom:          "Lupa",
            close_window:  "Zatvoriť okno",
        },
        "hu" => MenuStrings {
            about:         "A Visemte névjegye",
            check_updates: "Frissítések keresése\u{2026}",
            services:      "Szolgáltatások",
            hide:          "Visemte elrejtése",
            hide_others:   "Egyebek elrejtése",
            show_all:      "Összes megjelenítése",
            quit:          "Kilépés a Visemte-ből",
            edit:          "Szerkesztés",
            undo:          "Visszavonás",
            redo:          "Újra",
            cut:           "Kivágás",
            copy:          "Másolás",
            paste:         "Beillesztés",
            select_all:    "Összes kijelölése",
            view:          "Nézet",
            fullscreen:    "Teljes képernyő be/ki",
            window:        "Ablak",
            minimize:      "Minimalizálás",
            zoom:          "Nagyítás",
            close_window:  "Ablak bezárása",
        },
        "hr" => MenuStrings {
            about:         "O Visemteu",
            check_updates: "Provjeri ažuriranja\u{2026}",
            services:      "Usluge",
            hide:          "Sakrij Visemte",
            hide_others:   "Sakrij ostale",
            show_all:      "Prikaži sve",
            quit:          "Zatvori Visemte",
            edit:          "Uredi",
            undo:          "Poništi",
            redo:          "Ponovi",
            cut:           "Izreži",
            copy:          "Kopiraj",
            paste:         "Zalijepi",
            select_all:    "Odaberi sve",
            view:          "Prikaz",
            fullscreen:    "Uključi/isključi cijeli zaslon",
            window:        "Prozor",
            minimize:      "Minimiziraj",
            zoom:          "Zumiraj",
            close_window:  "Zatvori prozor",
        },
        "sl" => MenuStrings {
            about:         "O Visemteu",
            check_updates: "Preveri posodobitve\u{2026}",
            services:      "Storitve",
            hide:          "Skrij Visemte",
            hide_others:   "Skrij ostale",
            show_all:      "Prikaži vse",
            quit:          "Zapri Visemte",
            edit:          "Uredi",
            undo:          "Razveljavi",
            redo:          "Uveljavi",
            cut:           "Izreži",
            copy:          "Kopiraj",
            paste:         "Prilepi",
            select_all:    "Izberi vse",
            view:          "Pogled",
            fullscreen:    "Vklopi/izklopi celozaslonski način",
            window:        "Okno",
            minimize:      "Minimiziraj",
            zoom:          "Povečaj",
            close_window:  "Zapri okno",
        },
        "sv" => MenuStrings {
            about:         "Om Visemte",
            check_updates: "Sök efter uppdateringar\u{2026}",
            services:      "Tjänster",
            hide:          "Dölj Visemte",
            hide_others:   "Dölj andra",
            show_all:      "Visa alla",
            quit:          "Avsluta Visemte",
            edit:          "Redigera",
            undo:          "Ångra",
            redo:          "Gör om",
            cut:           "Klipp ut",
            copy:          "Kopiera",
            paste:         "Klistra in",
            select_all:    "Markera allt",
            view:          "Visa",
            fullscreen:    "Växla helskärm",
            window:        "Fönster",
            minimize:      "Minimera",
            zoom:          "Zooma",
            close_window:  "Stäng fönster",
        },
        "no" => MenuStrings {
            about:         "Om Visemte",
            check_updates: "Se etter oppdateringer\u{2026}",
            services:      "Tjenester",
            hide:          "Skjul Visemte",
            hide_others:   "Skjul andre",
            show_all:      "Vis alle",
            quit:          "Avslutt Visemte",
            edit:          "Rediger",
            undo:          "Angre",
            redo:          "Gjør om",
            cut:           "Klipp",
            copy:          "Kopier",
            paste:         "Lim inn",
            select_all:    "Merk alt",
            view:          "Vis",
            fullscreen:    "Veksle fullskjerm",
            window:        "Vindu",
            minimize:      "Minimer",
            zoom:          "Zoom",
            close_window:  "Lukk vindu",
        },
        "fi" => MenuStrings {
            about:         "Tietoja Visemtestä",
            check_updates: "Tarkista päivitykset\u{2026}",
            services:      "Palvelut",
            hide:          "Piilota Visemte",
            hide_others:   "Piilota muut",
            show_all:      "Näytä kaikki",
            quit:          "Lopeta Visemte",
            edit:          "Muokkaa",
            undo:          "Kumoa",
            redo:          "Tee uudelleen",
            cut:           "Leikkaa",
            copy:          "Kopioi",
            paste:         "Liitä",
            select_all:    "Valitse kaikki",
            view:          "Näytä",
            fullscreen:    "Vaihda koko näyttö",
            window:        "Ikkuna",
            minimize:      "Pienennä",
            zoom:          "Zoomaa",
            close_window:  "Sulje ikkuna",
        },
        "el" => MenuStrings {
            about:         "Σχετικά με το Visemte",
            check_updates: "Έλεγχος για ενημερώσεις\u{2026}",
            services:      "Υπηρεσίες",
            hide:          "Απόκρυψη Visemte",
            hide_others:   "Απόκρυψη άλλων",
            show_all:      "Εμφάνιση όλων",
            quit:          "Έξοδος από το Visemte",
            edit:          "Επεξεργασία",
            undo:          "Αναίρεση",
            redo:          "Επανάληψη",
            cut:           "Αποκοπή",
            copy:          "Αντιγραφή",
            paste:         "Επικόλληση",
            select_all:    "Επιλογή όλων",
            view:          "Προβολή",
            fullscreen:    "Εναλλαγή πλήρους οθόνης",
            window:        "Παράθυρο",
            minimize:      "Ελαχιστοποίηση",
            zoom:          "Ζουμ",
            close_window:  "Κλείσιμο παραθύρου",
        },
        // Default: English
        _ => MenuStrings {
            about:         "About Visemte",
            check_updates: "Check for Updates\u{2026}",
            services:      "Services",
            hide:          "Hide Visemte",
            hide_others:   "Hide Others",
            show_all:      "Show All",
            quit:          "Quit Visemte",
            edit:          "Edit",
            undo:          "Undo",
            redo:          "Redo",
            cut:           "Cut",
            copy:          "Copy",
            paste:         "Paste",
            select_all:    "Select All",
            view:          "View",
            fullscreen:    "Toggle Full Screen",
            window:        "Window",
            minimize:      "Minimize",
            zoom:          "Zoom",
            close_window:  "Close Window",
        },
    }
}

fn build_menu(app: &tauri::AppHandle) -> tauri::Result<Menu<tauri::Wry>> {
    let lang = system_lang();
    let s = menu_strings(&lang);

    let about = MenuItem::with_id(app, "about", s.about, true, None::<&str>)?;
    let check_updates = MenuItem::with_id(app, "check-updates", s.check_updates, true, None::<&str>)?;

    let app_menu = Submenu::with_items(
        app,
        "Visemte",
        true,
        &[
            &about,
            &check_updates,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::services(app, Some(s.services))?,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::hide(app, Some(s.hide))?,
            &PredefinedMenuItem::hide_others(app, Some(s.hide_others))?,
            &PredefinedMenuItem::show_all(app, Some(s.show_all))?,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::quit(app, Some(s.quit))?,
        ],
    )?;

    let edit_menu = Submenu::with_items(
        app,
        s.edit,
        true,
        &[
            &PredefinedMenuItem::undo(app, Some(s.undo))?,
            &PredefinedMenuItem::redo(app, Some(s.redo))?,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::cut(app, Some(s.cut))?,
            &PredefinedMenuItem::copy(app, Some(s.copy))?,
            &PredefinedMenuItem::paste(app, Some(s.paste))?,
            &PredefinedMenuItem::select_all(app, Some(s.select_all))?,
        ],
    )?;

    let view_menu = Submenu::with_items(
        app,
        s.view,
        true,
        &[
            &PredefinedMenuItem::fullscreen(app, Some(s.fullscreen))?,
        ],
    )?;

    let window_menu = Submenu::with_items(
        app,
        s.window,
        true,
        &[
            &PredefinedMenuItem::minimize(app, Some(s.minimize))?,
            &PredefinedMenuItem::maximize(app, Some(s.zoom))?,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::close_window(app, Some(s.close_window))?,
        ],
    )?;

    Menu::with_items(app, &[&app_menu, &edit_menu, &view_menu, &window_menu])
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .invoke_handler(tauri::generate_handler![app_target])
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_shell::init())
        .plugin(tauri_plugin_fs::init())
        .setup(|app| {
            if cfg!(debug_assertions) {
                app.handle().plugin(
                    tauri_plugin_log::Builder::default()
                        .level(log::LevelFilter::Info)
                        .build(),
                )?;
            }
            let menu = build_menu(app.handle())?;
            app.set_menu(menu)?;

            let handle = app.handle().clone();
            app.on_menu_event(move |_app, event| {
                if event.id() == "about" {
                    let _ = handle.emit("menu:about", ());
                } else if event.id() == "check-updates" {
                    let _ = handle.emit("menu:check-updates", ());
                }
            });

            Ok(())
        })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
